"""add address snapshot to orders

Revision ID: 1556981fb91a
Revises: 362e8cb6b564
Create Date: 2026-08-17 21:40:26.675871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1556981fb91a'
down_revision: Union[str, Sequence[str], None] = '362e8cb6b564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('recipient_name', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('recipient_phone', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('address_line_1', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('address_line_2', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('landmark', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('city', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('state', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('postal_code', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('country', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False))
    op.add_column('orders', sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False))
    op.add_column('orders', sa.Column('location_accuracy', sa.Numeric(precision=9, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'location_accuracy')
    op.drop_column('orders', 'longitude')
    op.drop_column('orders', 'latitude')
    op.drop_column('orders', 'country')
    op.drop_column('orders', 'postal_code')
    op.drop_column('orders', 'state')
    op.drop_column('orders', 'city')
    op.drop_column('orders', 'landmark')
    op.drop_column('orders', 'address_line_2')
    op.drop_column('orders', 'address_line_1')
    op.drop_column('orders', 'recipient_phone')
    op.drop_column('orders', 'recipient_name')
    # ### end Alembic commands ###
