"""create verification table

Revision ID: 352f059c75f2
Revises: ead3d0314050
Create Date: 2026-08-08 00:22:44.533780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '352f059c75f2'
down_revision: Union[str, Sequence[str], None] = 'ead3d0314050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifications', sa.Column('failed_attempts', sa.Integer(), nullable=False))
    op.drop_column('verifications', 'attempt_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifications', sa.Column('attempt_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('verifications', 'failed_attempts')
    # ### end Alembic commands ###
