"""create service type table

Revision ID: 3dc0699b51e6
Revises: d27fa8a7551d
Create Date: 2026-05-20 00:18:19.592344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dc0699b51e6'
down_revision: Union[str, Sequence[str], None] = 'd27fa8a7551d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_type',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.alter_column('order_status_history', 'status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('PENDING_PICKUP', 'PICKED_UP', 'RECEIVED', 'SORTING', 'WASHING', 'DRYING', 'PACKING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               existing_nullable=False,
               postgresql_using="status::orderstatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_status_history', 'status',
               existing_type=sa.Enum('PENDING_PICKUP', 'PICKED_UP', 'RECEIVED', 'SORTING', 'WASHING', 'DRYING', 'PACKING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.drop_table('service_type')
    # ### end Alembic commands ###
