"""add service type relationship to laundry item

Revision ID: 9c6977d1dc9c
Revises: 3dc0699b51e6
Create Date: 2026-05-20 00:48:32.160972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c6977d1dc9c'
down_revision: Union[str, Sequence[str], None] = '3dc0699b51e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with a temporary server_default so Postgres can add it safely
    op.add_column(
        'laundry_items',
        sa.Column(
            'service_type_id',
            sa.Uuid(),
            nullable=True,
            server_default=sa.text("'00000000-0000-0000-0000-000000000001'::uuid")
        )
    )

    # Ensure a default service_type exists to reference for backfilling existing rows.
    # Use a fixed UUID so the row can be referenced deterministically.
    op.execute("""
    INSERT INTO service_type (id, name, description, current_price, is_active, created_at, updated_at)
    VALUES ('00000000-0000-0000-0000-000000000001', 'Default', 'Auto-created default service', 0.00, true, now(), now())
    ON CONFLICT (id) DO NOTHING;
    """)

    # Backfill existing laundry_items to reference the default service type
    op.execute("""
    UPDATE laundry_items SET service_type_id = '00000000-0000-0000-0000-000000000001' WHERE service_type_id IS NULL;
    """)

    # Make column NOT NULL now that existing rows are backfilled
    op.alter_column('laundry_items', 'service_type_id', existing_type=sa.Uuid(), nullable=False)

    # Remove the temporary server_default
    op.alter_column('laundry_items', 'service_type_id', existing_type=sa.Uuid(), server_default=None)

    # Finally add foreign key constraint
    op.create_foreign_key(None, 'laundry_items', 'service_type', ['service_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'laundry_items', type_='foreignkey')
    op.drop_column('laundry_items', 'service_type_id')
    # ### end Alembic commands ###
