"""create verification table

Revision ID: b2c689534d23
Revises: 352f059c75f2
Create Date: 2026-08-08 00:34:46.430276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c689534d23'
down_revision: Union[str, Sequence[str], None] = '352f059c75f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifications', sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifications', 'invalidated_at')
    # ### end Alembic commands ###
