"""create verification table

Revision ID: ead3d0314050
Revises: ea7c0cbc70b4
Create Date: 2026-08-08 00:19:28.692501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead3d0314050'
down_revision: Union[str, Sequence[str], None] = 'ea7c0cbc70b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Enum('EMAIL_VERIFICATION', 'PASSWORD_RESET', 'EMAIL_CHANGE', 'PHONE_VERIFICATION', name='verificationpurpose'), nullable=False),
    sa.Column('token_hash', sa.String(length=256), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_expires_at'), 'verifications', ['expires_at'], unique=False)
    op.create_index(op.f('ix_verifications_identifier'), 'verifications', ['identifier'], unique=False)
    op.create_index(op.f('ix_verifications_purpose'), 'verifications', ['purpose'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifications_purpose'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_identifier'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_expires_at'), table_name='verifications')
    op.drop_table('verifications')
    # ### end Alembic commands ###
