from enum import Enum

class UserRole(str, Enum):
    CUSTOMER = "CUSTOMER"
    STAFF = "STAFF"
    DELIVERY_AGENT = "DELIVERY_AGENT"
    ADMIN = "ADMIN"
    
class OrderStatus(str,Enum):
    PENDING_PICKUP = 'PENDING_PICKUP'
    PICKED_UP = 'PICKED_UP'
    RECEIVED = 'RECEIVED'
    
    SORTING = 'SORTING'
    WASHING = 'WASHING'
    DRYING = 'DRYING'
    IRONING = 'IRONING'
    PACKING = 'PACKING'
    
    OUT_FOR_DELIVERY= 'OUT_FOR_DELIVERY'
    DELIVERED='DELIVERED'
    
    CANCELLED='CANCELLED'

class DeviceType(str, Enum):
    WEB = 'WEB'
    MOBILE = 'MOBILE'
    TABLET = 'TABLET'
    DESKTOP = 'DESKTOP'

class VerificationPurpose(str, Enum):
    EMAIL_VERIFICATION = "EMAIL_VERIFICATION"
    PASSWORD_RESET = "PASSWORD_RESET"
    EMAIL_CHANGE = "EMAIL_CHANGE"
    PHONE_VERIFICATION = "PHONE_VERIFICATION"